### ISSUE TITLE
Add cookie notice

### ISSUE THREAD

**Issue by jesusfer** [comicagg/comicagg#14]
### Tasks

- [x] Add a privacy and cookie policy
- [x] Add cookie consent in the page and link to policies
- [x] Handle rejected consent
- [x] Move contact view to new module
- [ ] Disable the login button if cookies are not accepted
